{% set name = "testcontainers" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/testcontainers-{{ version }}.tar.gz
  sha256: e8610985cae2f0bc4bc3991896a47d5547f3ed896192970826151059a75f4ac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - docker-py
    - urllib3
    - wrapt
    - typing-extensions
  run_constrained:
    - python-arango >=7.8.0,<8.0.0
    - azure-storage-blob >=12.19.0,<13.0.0
    - clickhouse-driver *
    - google-cloud-pubsub >=2
    - google-cloud-datastore >=2
    - influxdb *
    - influxdb-client *
    - python-kubernetes *
    - pyyaml *
    - python-keycloak *
    - boto3 *
    - minio *
    - nats-py *
    - pymongo *
    - sqlalchemy *
    - pymssql *
    - pymysql *
    - neo4j-python-driver *
    - opensearch-py *
    - oracledb *
    - pika *
    - redis-py *
    - selenium *
    - weaviate-client >=4.5.4,<5.0.0
    - chromadb-client *
    - qdrant-client *
    - bcrypt *

test:
  imports:
    - testcontainers
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library for throwaway instances of anything that can run in a Docker container
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - andysham
